services:
  mongodb:
    image: mongo:7.0
    container_name: mern-mongodb
    restart: "no"
    environment:
      MONGO_INITDB_ROOT_USERNAME_FILE: /run/secrets/mongo-root-username
      MONGO_INITDB_ROOT_PASSWORD_FILE: /run/secrets/mongo-root-password
      MONGO_INITDB_DATABASE: ${MONGO_INITDB_DATABASE}
    secrets:
      - mongo-root-username
      - mongo-root-password
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
      - mongodb_configdb:/data/configdb
      - ./docker/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    networks:
      - app-network

  server:
    build:
      context: ./server
      dockerfile: Dockerfile
      target: development
    container_name: mern-server
    restart: "no"
    working_dir: /app
    environment:
      - NODE_ENV=${NODE_ENV}
      - PORT=${PORT}
      - DATABASE_TYPE=${DATABASE_TYPE}
      - MONGODB_URI=${MONGODB_URI}
      - CLIENT_URL=${CLIENT_URL}
      - JWT_SECRET=${JWT_SECRET}
      - JWT_EXPIRE=${JWT_EXPIRE}
    command: sh -c "npm install && npm run dev"
    ports:
      - "5001:5001"
    volumes:
      - ./server:/app
    depends_on:
      - mongodb
    networks:
      - app-network

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
      target: development
    container_name: mern-client
    restart: "no"
    working_dir: /app
    environment:
      - REACT_APP_API_URL=${REACT_APP_API_URL}
      - PORT=3001
    command: sh -c "npm install && npm run dev"
    ports:
      - "3001:3001"
    volumes:
      - ./client:/app
    depends_on:
      - server
    networks:
      - app-network

volumes:
  mongodb_data:
  mongodb_configdb:

networks:
  app-network:
    driver: bridge

secrets:
  mongo-root-username:
    file: ./docker/secrets/mongo-root-username.txt
  mongo-root-password:
    file: ./docker/secrets/mongo-root-password.txt
